[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vote_program_sol_a = "vod1XRnwFrQGfzhQjR15iEUz4WFxiyXBkTUk7jvxUHJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/macbookpro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
